### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jurihock** [jurihock/stftPitchShiftPlugin#1]
- [ ] Explore the variable block length in `processBlock`
- [ ] Add performance measurements
- [ ] Try different FFT backend (PocketFFT, JUCE FFT)
- [ ] Maybe add a configurable gain for each pitch shifting stage
- [ ] Think about advanced automation, maybe something with MIDI chord recognition

**Comment by jurihock** [comment]
It looks like the Logic is reporting the completely wrong (or maybe the max. possible, but still not the configured in audio settings) block size in `prepareToPlay` and the correct one (configured) in `processBlock`.  So we have to be ready to dynamically adapt the block size reported in `processBlock` by reallocating the `Core` instance.
